MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()

FUNCTION(GENERIC_LOG)
    MESSAGE("### Currently processing dir: ${CMAKE_CURRENT_SOURCE_DIR} ###")
ENDFUNCTION()
